"use client";

import React from "react";
import Link from "next/link";

export default function AboutUs() {
  const pillars = [
    {
      title: "100% Accessible",
      desc: "No rooftops, no structural leases, no housing permissions. Whether you rent a studio flat or own a condo, clean energy is now within your reach.",
      icon: "🌐",
    },
    {
      title: "Radically Transparent",
      desc: "Track every single watt generated by your panels in real time. We provide audited ledger exports and clear DISCOM credit transfer verification.",
      icon: "📊",
    },
    {
      title: "True Sustainability",
      desc: "Every virtual panel hosted adds actual new solar capacity to the regional grid, actively displacing fossil fuels and reducing real carbon footprints.",
      icon: "🌿",
    },
  ];

  const team = [
    {
      name: "Mathew Laimayum",
      role: "Co-Founder, Finance & Strategy",
      bio: "Mathew leads project acquisition, financial structuring, and host agreements. He is dedicated to building sustainable, high-yield digital asset models for retail consumers.",
      img: "👤",
    },
    {
      name: "Naseer Sathyala",
      role: "Co-Founder, Tech & Infrastructure",
      bio: "Naseer manages platform architecture, industrial IoT telemetry integration, and utility billing API integrations to ensure seamless credit distribution.",
      img: "💻",
    },
  ];

  return (
    <>
      <div className="about-us-page">
        {/* Background decorative glows */}
        <div className="glow-bg pulse-glow" style={{ top: "15%", left: "5%" }} />
        <div className="glow-bg-blue" style={{ bottom: "15%", right: "10%" }} />

        {/* Hero Section */}
        <section className="about-hero section-padding">
          <div className="container text-center-ab">
            <span className="badge">Our Purpose</span>
            <h1>Democratizing Solar for Everyone</h1>
            <p className="ab-subtitle">
              Cloud Solar was founded to break down the physical barriers of clean energy. We believe that choosing solar should be as simple as subscribing to a digital service.
            </p>
          </div>
        </section>

        {/* Mission / Context Section */}
        <section className="section-padding mission-section">
          <div className="container">
            <div className="grid-2">
              <div className="mission-content">
                <span className="badge">The Problem we Solve</span>
                <h2>Why Virtual Solar Matters</h2>
                <p>
                  Urban areas are expanding rapidly, with more people living in high-rise apartments, condominiums, or rented homes. For over 90% of urban residents, traditional rooftop solar is physically impossible:
                </p>
                <ul className="ab-list">
                  <li><strong>Lack of Roof Ownership:</strong> Tenants and apartment owners don't own the roofs.</li>
                  <li><strong>Heavy Capital Barrier:</strong> Standard rooftop solar arrays cost ₹3L - ₹5L, a massive hurdle.</li>
                  <li><strong>Shaded Layouts:</strong> Urban trees and neighboring buildings cause high shading, making systems inefficient.</li>
                </ul>
                <p className="highlight-text">
                  Cloud Solar bridges this gap. By building co-located industrial solar parks and slicing digital panel allocations, we allow you to start your solar transition instantly, with just one panel, from any flat or rental home.
                </p>
              </div>

              {/* Decorative card block */}
              <div className="card-glass mission-quote-card">
                <div className="quote-icon">“</div>
                <blockquote>
                  Our mission is to decouple the physical location of solar generation from the location of consumption. We want to empower every citizen to hold a stake in clean energy grids.
                </blockquote>
                <div className="quote-author">
                  <div className="qa-dot" />
                  <div>
                    <strong>Mathew & Naseer</strong>
                    <span>Founding Team, Cloud Solar</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Core Pillars */}
        <section className="section-padding pillars-section">
          <div className="container">
            <div className="section-title-center">
              <span className="badge">Our Values</span>
              <h2>Built on Three Core Pillars</h2>
              <p>We are reimagining clean energy with a foundation of inclusivity and transparency.</p>
            </div>

            <div className="grid-3">
              {pillars.map((pil, idx) => (
                <div key={idx} className="pillar-card card-glass">
                  <div className="pillar-icon">{pil.icon}</div>
                  <h3>{pil.title}</h3>
                  <p>{pil.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Team Section */}
        <section className="section-padding team-section">
          <div className="container">
            <div className="section-title-center">
              <span className="badge">The Team</span>
              <h2>Meet the Founders</h2>
              <p>A group of developers, clean-energy enthusiasts, and finance experts reshaping solar accessibility.</p>
            </div>

            <div className="team-grid">
              {team.map((member, idx) => (
                <div key={idx} className="team-card card-glass">
                  <div className="team-avatar-placeholder">
                    {/* SVG Avatar for professional clean look */}
                    <svg width="100" height="100" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <circle cx="50" cy="50" r="48" fill="var(--primary-glow-subtle)" stroke="var(--primary)" strokeWidth="2" />
                      <circle cx="50" cy="40" r="16" fill="var(--primary)" />
                      <path d="M18 80C18 65 32 58 50 58C68 58 82 65 82 80" fill="var(--primary)" />
                      {/* Technical overlay grid */}
                      <path d="M50 2v96M2 50h96" stroke="rgba(255,255,255,0.05)" strokeWidth="1" />
                    </svg>
                  </div>
                  <h3>{member.name}</h3>
                  <span className="team-role">{member.role}</span>
                  <p className="team-bio">{member.bio}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Call to Action */}
        <section className="ab-cta-section section-padding">
          <div className="container text-center-ab">
            <div className="card-glass ab-cta-card">
              <h2>Let's Accelerate the Transition</h2>
              <p>Ready to transition to solar hosting? Reserve panels in our upcoming industrial grids today.</p>
              <div className="ab-cta-buttons">
                <Link href="/" className="btn-primary">
                  Go to Calculator
                </Link>
                <Link href="/how-it-works" className="btn-secondary">
                  How It Works &rarr;
                </Link>
              </div>
            </div>
          </div>
        </section>
      </div>

      {/* Local styles for About Us page */}
      <style jsx>{`
        .about-us-page {
          position: relative;
        }

        .text-center-ab {
          text-align: center;
          max-width: 700px;
          margin: 0 auto;
        }

        .ab-subtitle {
          color: var(--text-secondary);
          font-size: 1.25rem;
          line-height: 1.6;
          margin-top: 20px;
        }

        /* Mission section list */
        .mission-content h2 {
          font-size: 2.25rem;
          margin-bottom: 20px;
        }

        .mission-content p {
          color: var(--text-secondary);
          font-size: 1.05rem;
          line-height: 1.6;
          margin-bottom: 24px;
        }

        .ab-list {
          list-style: none;
          display: flex;
          flex-direction: column;
          gap: 16px;
          margin-bottom: 28px;
          padding-left: 8px;
        }

        .ab-list li {
          color: var(--text-secondary);
          font-size: 0.95rem;
          position: relative;
          padding-left: 20px;
          line-height: 1.5;
        }

        .ab-list li::before {
          content: '→';
          position: absolute;
          left: 0;
          color: var(--primary);
          font-weight: 700;
        }

        .ab-list li strong {
          color: var(--text-primary);
        }

        .highlight-text {
          border-left: 3px solid var(--primary);
          padding-left: 20px;
          font-style: italic;
          background: var(--primary-glow-subtle);
          padding-top: 12px;
          padding-bottom: 12px;
          border-radius: 0 var(--border-radius-sm) var(--border-radius-sm) 0;
        }

        /* Mission Quote Card */
        .mission-quote-card {
          padding: 48px;
          display: flex;
          flex-direction: column;
          justify-content: center;
        }

        .quote-icon {
          font-size: 4rem;
          line-height: 1;
          color: var(--primary);
          font-family: var(--font-family-title);
          height: 30px;
          margin-bottom: 10px;
        }

        blockquote {
          font-size: 1.25rem;
          line-height: 1.6;
          font-style: italic;
          color: var(--text-primary);
          margin-bottom: 32px;
          font-family: var(--font-family-title);
        }

        .quote-author {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .qa-dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
          background: var(--primary);
          box-shadow: 0 0 8px var(--primary);
        }

        .quote-author strong {
          display: block;
          color: var(--text-primary);
          font-size: 0.95rem;
        }

        .quote-author span {
          color: var(--text-muted);
          font-size: 0.8rem;
        }

        /* Pillars cards */
        .pillar-card {
          padding: 40px 32px;
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .pillar-icon {
          font-size: 2.5rem;
          margin-bottom: 8px;
        }

        .pillar-card h3 {
          font-size: 1.3rem;
          color: var(--text-primary);
        }

        .pillar-card p {
          font-size: 0.9rem;
          color: var(--text-secondary);
          line-height: 1.6;
        }

        /* Team cards */
        .team-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 40px;
          max-width: 800px;
          margin: 0 auto;
        }

        @media (max-width: 768px) {
          .team-grid {
            grid-template-columns: 1fr;
            gap: 32px;
          }
        }

        .team-card {
          padding: 40px;
          text-align: center;
          display: flex;
          flex-direction: column;
          align-items: center;
        }

        .team-avatar-placeholder {
          margin-bottom: 24px;
          width: 100px;
          height: 100px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          position: relative;
        }

        .team-card h3 {
          font-size: 1.4rem;
          margin-bottom: 4px;
        }

        .team-role {
          font-size: 0.85rem;
          color: var(--primary);
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          margin-bottom: 20px;
        }

        .team-bio {
          font-size: 0.9rem;
          color: var(--text-secondary);
          line-height: 1.6;
        }

        /* CTA card */
        .ab-cta-card {
          padding: 60px 40px;
          max-width: 800px;
          margin: 0 auto;
        }

        .ab-cta-card h2 {
          font-size: 2.2rem;
          margin-bottom: 12px;
        }

        .ab-cta-card p {
          color: var(--text-secondary);
          font-size: 1.05rem;
          max-width: 550px;
          margin: 0 auto 32px;
        }

        .ab-cta-buttons {
          display: flex;
          justify-content: center;
          gap: 16px;
        }

        @media (max-width: 576px) {
          .mission-quote-card {
            padding: 24px 16px;
          }
          blockquote {
            font-size: 1.05rem;
            margin-bottom: 20px;
          }
          .pillar-card {
            padding: 24px 16px;
          }
          .team-card {
            padding: 24px 16px;
          }
          .ab-cta-card {
            padding: 40px 16px;
          }
          .ab-cta-buttons {
            flex-direction: column;
            gap: 12px;
          }
        }
      `}</style>
    </>
  );
}
