"use client";

import React, { useState } from "react";
import Link from "next/link";
import Calculator from "@/components/Calculator";

export default function Home() {
  const [activeFaq, setActiveFaq] = useState(null);

  const toggleFaq = (index) => {
    if (activeFaq === index) {
      setActiveFaq(null);
    } else {
      setActiveFaq(index);
    }
  };

  const comparisonData = [
    {
      title: "Rooftop Solar",
      badge: "Traditional",
      points: [
        { label: "Rooftop Space", val: "Required (100+ sq ft)", status: "bad" },
        { label: "Upfront Cost", val: "High (~₹3L - ₹5L)", status: "bad" },
        { label: "Maintenance", val: "Self-managed, cleaning & repair", status: "bad" },
        { label: "Portability", val: "Fixed. Cannot move if you shift", status: "bad" },
        { label: "Eligibility", val: "Only for independent house owners", status: "bad" },
      ],
    },
    {
      title: "Cloud Solar",
      badge: "The Smart Choice",
      highlight: true,
      points: [
        { label: "Rooftop Space", val: "Zero space needed", status: "good" },
        { label: "Upfront Cost", val: "Flexible (Start with 1 panel)", status: "good" },
        { label: "Maintenance", val: "100% managed by Cloud Solar", status: "good" },
        { label: "Portability", val: "100% portable across state grid", status: "good" },
        { label: "Eligibility", val: "Anyone, including tenants & flats", status: "good" },
      ],
    },
  ];

  const projects = [
    {
      id: "project-1",
      name: "EcoPark Commercial Rooftop I",
      location: "Bengaluru, Karnataka",
      capacity: "180 kW",
      progress: 100,
      yield: "140 units/kW/month",
      status: "Fully Funded",
      partner: "Kanakapura Industrial Area",
    },
    {
      id: "project-2",
      name: "Apex Logistics Warehouse Solar",
      location: "Chennai, Tamil Nadu",
      capacity: "350 kW",
      progress: 68,
      yield: "135 units/kW/month",
      status: "Active Hosting",
      partner: "Sriperumbudur Hub",
    },
    {
      id: "project-3",
      name: "Summit Corporate Center II",
      location: "Hyderabad, Telangana",
      capacity: "240 kW",
      progress: 35,
      yield: "142 units/kW/month",
      status: "Hosting Open",
      partner: "Gachibowli Tech District",
    },
  ];

  const faqs = [
    {
      question: "What is Cloud Solar?",
      answer: "Cloud Solar is a virtual solar hosting platform. We partner with commercial and industrial properties to set up large-scale solar installations. You can purchase solar panels virtually in these installations. The clean energy generated is fed into the state grid, and the equivalent solar billing credits are sent directly to offset your household utility electricity bills.",
    },
    {
      question: "How do I receive electricity bill credits?",
      answer: "The electricity credits generated by your panels are transferred to your state utility consumer number (e.g., BESCOM, TNEB, TSSPDCL) via net-billing regulations. Every month, your electricity bill is updated with 'Solar Credits' from Cloud Solar, reducing the total amount you owe.",
    },
    {
      question: "Is it portable? What if I move houses?",
      answer: "Yes, 100%! Since your solar panels are virtual and the billing is digital, you do not need to uninstall any physical hardware. If you move anywhere within the same state utility grid, simply update your Consumer Account ID in your Cloud Solar dashboard, and your billing offsets will start transferring to your new home.",
    },
    {
      question: "How long do the solar assets last?",
      answer: "Our co-hosting agreements and panel lifetimes span 25 years. You receive billing offsets for the entire 25-year lifespan of the physical panels. We provide full performance guarantees and insurance coverage throughout.",
    },
    {
      question: "Who takes care of the solar panel maintenance?",
      answer: "We handle 100% of the maintenance. We wash the panels, monitor generation, and handle any grid connection repairs with professional EPC partners. Operation and maintenance costs are deducted directly from the gross generation, so you never pay any out-of-pocket maintenance fees.",
    },
  ];

  return (
    <>
      {/* Hero Section */}
      <section className="hero-section">
        <div className="glow-bg pulse-glow" style={{ top: "-10%", left: "10%" }} />
        <div className="glow-bg-blue" style={{ top: "30%", right: "5%" }} />

        <div className="container hero-grid">
          <div className="hero-content">
            <div className="badge">INTRODUCING VIRTUAL HOSTING</div>
            <h1>
              Own Solar. <br />
              <span className="text-gradient">Without the installation.</span>
            </h1>
            <p className="hero-desc">
              Harness clean solar energy and lower your electricity bills without having a rooftop. Host panels virtually on our pre-built industrial hubs and receive credits directly on your power utility account.
            </p>
            <div className="hero-actions">
              <a href="#calculator" className="btn-primary">
                Calculate Savings
              </a>
              <Link href="/how-it-works" className="btn-secondary">
                See How It Works &rarr;
              </Link>
            </div>
            
            <div className="hero-stats">
              <div className="stat-item">
                <span className="stat-num text-gradient">2,500+</span>
                <span className="stat-lbl">Active Panels Hosted</span>
              </div>
              <div className="stat-divider" />
              <div className="stat-item">
                <span className="stat-num text-gradient">₹45L+</span>
                <span className="stat-lbl">Monthly Bills Saved</span>
              </div>
              <div className="stat-divider" />
              <div className="stat-item">
                <span className="stat-num text-gradient">320T</span>
                <span className="stat-lbl">CO2 Emissions Reduced</span>
              </div>
            </div>
          </div>

          {/* Interactive Hero Graphic (Dashboard Replica) */}
          <div className="hero-graphic">
            <div className="card-glass graphic-dashboard">
              <div className="dash-header">
                <div className="dash-dot-grid">
                  <span className="dot red" />
                  <span className="dot yellow" />
                  <span className="dot green" />
                </div>
                <div className="dash-title">Cloud Solar Dashboard</div>
              </div>
              <div className="dash-body">
                <div className="dash-metric-row">
                  <div className="dash-metric-card card-forest">
                    <span className="dm-lbl">My Virtual Panels</span>
                    <span className="dm-val">12 Panels (1.2 kW)</span>
                  </div>
                  <div className="dash-metric-card card-forest">
                    <span className="dm-lbl">Today's Generation</span>
                    <span className="dm-val">5.8 kWh</span>
                  </div>
                </div>
                
                {/* Generation Chart Representation */}
                <div className="dash-chart card-glass">
                  <div className="chart-header">
                    <span>Solar Yield Grid (Daily)</span>
                    <span className="live-indicator"><span className="pulse-dot"></span> LIVE</span>
                  </div>
                  <div className="chart-bars">
                    <div className="bar-wrapper"><div className="bar" style={{ height: "45%" }} /><span className="bar-lbl">Mon</span></div>
                    <div className="bar-wrapper"><div className="bar" style={{ height: "60%" }} /><span className="bar-lbl">Tue</span></div>
                    <div className="bar-wrapper"><div className="bar" style={{ height: "85%" }} /><span className="bar-lbl">Wed</span></div>
                    <div className="bar-wrapper"><div className="bar active" style={{ height: "95%" }} /><span className="bar-lbl">Thu</span></div>
                    <div className="bar-wrapper"><div className="bar" style={{ height: "70%" }} /><span className="bar-lbl">Fri</span></div>
                    <div className="bar-wrapper"><div className="bar" style={{ height: "50%" }} /><span className="bar-lbl">Sat</span></div>
                    <div className="bar-wrapper"><div className="bar" style={{ height: "40%" }} /><span className="bar-lbl">Sun</span></div>
                  </div>
                </div>

                <div className="dash-billing card-forest">
                  <div className="billing-title">Utility Balance Offset</div>
                  <div className="billing-flow">
                    <span className="bf-party">BESCOM Grid</span>
                    <span className="bf-arrow">&larr; ₹1,850 Credits Transferred &larr;</span>
                    <span className="bf-party mine">My Account</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Comparisons Section */}
      <section className="section-padding comparison-section">
        <div className="container">
          <div className="section-title-center">
            <span className="badge">Comparison</span>
            <h2>Why Virtual Solar?</h2>
            <p>Traditional rooftop setups can be complex. See how Cloud Solar simplifies ownership.</p>
          </div>

          <div className="comparison-grid">
            {comparisonData.map((comp, idx) => (
              <div
                key={idx}
                className={`comparison-card card-glass ${comp.highlight ? "highlighted-card" : ""}`}
              >
                {comp.highlight && <div className="card-top-tag">Recommended</div>}
                <div className="comp-card-header">
                  <span className="comp-badge">{comp.badge}</span>
                  <h3>{comp.title}</h3>
                </div>
                <div className="comp-points">
                  {comp.points.map((pt, pIdx) => (
                    <div key={pIdx} className="comp-point-row">
                      <span className="pt-label">{pt.label}</span>
                      <div className="pt-val-wrap">
                        <span className={`pt-icon ${pt.status === "good" ? "check" : "cross"}`}>
                          {pt.status === "good" ? "✓" : "✗"}
                        </span>
                        <span className={`pt-value ${pt.status === "good" ? "green" : "muted"}`}>{pt.val}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Calculator Section */}
      <section id="calculator" className="section-padding calculator-section">
        <div className="glow-bg" style={{ bottom: "-10%", right: "10%" }} />
        <div className="container">
          <Calculator />
        </div>
      </section>

      {/* Active Solar Projects */}
      <section className="section-padding projects-section">
        <div className="container">
          <div className="section-title-center">
            <span className="badge">Live Grids</span>
            <h2>Our Hosted Solar Parks</h2>
            <p>We deploy standard Tier-1 solar panels on high-exposure corporate rooftops.</p>
          </div>

          <div className="grid-3">
            {projects.map((proj) => (
              <div key={proj.id} className="project-card card-glass">
                <div className="project-img-placeholder">
                  {/* Clean SVG Illustration representing rooftop solar grid */}
                  <svg width="100%" height="150" viewBox="0 0 200 120" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect width="200" height="120" fill="#0B1426" />
                    {/* Perspective Roof Grids */}
                    <path d="M20 100L80 20H120L180 100H20Z" fill="#0D2A22" stroke="var(--primary)" strokeWidth="1" opacity="0.3" />
                    <line x1="80" y1="20" x2="20" y2="100" stroke="rgba(0, 230, 153, 0.4)" strokeWidth="1" />
                    <line x1="100" y1="20" x2="100" y2="100" stroke="rgba(0, 230, 153, 0.4)" strokeWidth="1" />
                    <line x1="120" y1="20" x2="180" y2="100" stroke="rgba(0, 230, 153, 0.4)" strokeWidth="1" />
                    <line x1="50" y1="60" x2="150" y2="60" stroke="rgba(0, 230, 153, 0.4)" strokeWidth="1" />
                    {/* Glowing Sun */}
                    <circle cx="100" cy="30" r="10" fill="#00E699" filter="drop-shadow(0 0 8px #00E699)" />
                    {/* Panel symbols */}
                    <rect x="75" y="70" width="15" height="10" rx="1" fill="#00D2FF" opacity="0.8" />
                    <rect x="95" y="70" width="15" height="10" rx="1" fill="#00D2FF" opacity="0.8" />
                    <rect x="115" y="70" width="15" height="10" rx="1" fill="#00D2FF" opacity="0.8" />
                  </svg>
                  <span className="proj-status-tag">{proj.status}</span>
                </div>
                <div className="proj-details">
                  <div className="proj-loc">📍 {proj.location}</div>
                  <h3>{proj.name}</h3>
                  <p className="proj-partner">Host Partner: {proj.partner}</p>
                  
                  <div className="proj-specs">
                    <div>
                      <span className="ps-lbl">System Size</span>
                      <span className="ps-val">{proj.capacity}</span>
                    </div>
                    <div>
                      <span className="ps-lbl">Monthly Yield</span>
                      <span className="ps-val">{proj.yield}</span>
                    </div>
                  </div>

                  {/* Progress Bar */}
                  <div className="proj-progress-wrap">
                    <div className="progress-lbl-row">
                      <span>Co-Hosted Allocation</span>
                      <span>{proj.progress}%</span>
                    </div>
                    <div className="progress-track">
                      <div className="progress-bar" style={{ width: `${proj.progress}%` }} />
                    </div>
                  </div>

                  <button className="btn-secondary btn-proj" disabled={proj.progress === 100}>
                    {proj.progress === 100 ? "Fully Subscribed" : "Co-Host Panels"}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="section-padding faq-section">
        <div className="container">
          <div className="section-title-center">
            <span className="badge">Common Queries</span>
            <h2>Frequently Asked Questions</h2>
            <p>Everything you need to know about starting your virtual solar savings.</p>
          </div>

          <div className="faq-list">
            {faqs.map((faq, index) => {
              const isOpen = activeFaq === index;
              return (
                <div key={index} className={`faq-item ${isOpen ? "faq-item-open" : ""}`}>
                  <button className="faq-question" onClick={() => toggleFaq(index)}>
                    <span>{faq.question}</span>
                    <span className="faq-chevron">
                      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <polyline points="6 9 12 15 18 9"></polyline>
                      </svg>
                    </span>
                  </button>
                  <div className="faq-answer-container">
                    <div className="faq-answer">
                      <p>{faq.answer}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CSS Styles specific to Home page elements */}
      <style jsx>{`
        /* Hero section styling */
        .hero-section {
          padding: 120px 0 80px;
          position: relative;
          overflow: hidden;
        }

        .hero-grid {
          display: grid;
          grid-template-columns: 1.12fr 0.88fr;
          gap: 60px;
          align-items: center;
        }

        @media (max-width: 968px) {
          .hero-grid {
            grid-template-columns: 1fr;
            gap: 48px;
            text-align: center;
          }
        }

        .hero-content {
          z-index: 10;
        }

        .hero-content h1 {
          font-size: 3.5rem;
          line-height: 1.15;
          margin-bottom: 24px;
        }

        @media (max-width: 576px) {
          .hero-content h1 {
            font-size: 2.5rem;
          }
        }

        .hero-desc {
          color: var(--text-secondary);
          font-size: 1.15rem;
          line-height: 1.6;
          margin-bottom: 36px;
          max-width: 580px;
        }

        @media (max-width: 968px) {
          .hero-desc {
            margin-left: auto;
            margin-right: auto;
          }
        }

        .hero-actions {
          display: flex;
          gap: 16px;
          margin-bottom: 48px;
        }

        @media (max-width: 968px) {
          .hero-actions {
            justify-content: center;
          }
        }

        @media (max-width: 480px) {
          .hero-actions {
            flex-direction: column;
          }
        }

        .hero-stats {
          display: flex;
          align-items: center;
          gap: 24px;
        }

        @media (max-width: 968px) {
          .hero-stats {
            justify-content: center;
          }
        }

        @media (max-width: 480px) {
          .hero-stats {
            flex-direction: column;
            gap: 16px;
          }
          .stat-divider {
            display: none;
          }
        }

        .stat-item {
          display: flex;
          flex-direction: column;
        }

        .stat-num {
          font-family: var(--font-family-title);
          font-weight: 800;
          font-size: 2rem;
          line-height: 1.2;
        }

        .stat-lbl {
          font-size: 0.8rem;
          color: var(--text-muted);
          text-transform: uppercase;
          margin-top: 4px;
          letter-spacing: 0.05em;
        }

        .stat-divider {
          width: 1px;
          height: 40px;
          background: rgba(255, 255, 255, 0.1);
        }

        /* Hero Graphic styling */
        .hero-graphic {
          position: relative;
          z-index: 10;
          perspective: 1000px;
        }

        .graphic-dashboard {
          transform: rotateY(-8deg) rotateX(4deg);
          box-shadow: -20px 20px 40px rgba(0,0,0,0.5);
          border-color: rgba(255, 255, 255, 0.06);
          padding: 24px;
        }

        @media (max-width: 968px) {
          .graphic-dashboard {
            transform: none;
            max-width: 480px;
            margin: 0 auto;
          }
        }

        .dash-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
          padding-bottom: 14px;
          margin-bottom: 20px;
        }

        .dash-dot-grid {
          display: flex;
          gap: 6px;
        }

        .dash-dot-grid .dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
        }

        .dash-dot-grid .dot.red { background: #ff5f56; }
        .dash-dot-grid .dot.yellow { background: #ffbd2e; }
        .dash-dot-grid .dot.green { background: #27c93f; }

        .dash-title {
          font-size: 0.75rem;
          color: var(--text-muted);
          text-transform: uppercase;
          letter-spacing: 0.1em;
        }

        .dash-metric-row {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 16px;
          margin-bottom: 20px;
        }

        .dash-metric-card {
          padding: 16px;
        }

        .dm-lbl {
          display: block;
          font-size: 0.75rem;
          color: var(--text-secondary);
          margin-bottom: 4px;
        }

        .dm-val {
          font-family: var(--font-family-title);
          font-weight: 700;
          font-size: 1rem;
          color: var(--primary);
        }

        .dash-chart {
          background: rgba(255, 255, 255, 0.01);
          padding: 16px;
          margin-bottom: 20px;
        }

        .chart-header {
          display: flex;
          justify-content: space-between;
          font-size: 0.8rem;
          color: var(--text-secondary);
          margin-bottom: 16px;
        }

        .live-indicator {
          color: var(--primary);
          font-weight: 700;
          display: flex;
          align-items: center;
          gap: 6px;
        }

        .pulse-dot {
          width: 6px;
          height: 6px;
          border-radius: 50%;
          background: var(--primary);
          animation: pulseGlow 1.5s infinite;
        }

        .chart-bars {
          display: flex;
          justify-content: space-between;
          align-items: flex-end;
          height: 80px;
        }

        .bar-wrapper {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 8px;
          flex: 1;
        }

        .bar {
          width: 12px;
          background: rgba(255, 255, 255, 0.08);
          border-radius: 6px 6px 0 0;
          transition: height 0.5s ease;
        }

        .bar.active, .bar:hover {
          background: linear-gradient(180deg, var(--primary), var(--secondary));
          filter: drop-shadow(0 0 4px var(--primary-glow));
        }

        .bar-lbl {
          font-size: 0.65rem;
          color: var(--text-muted);
        }

        .dash-billing {
          padding: 12px;
        }

        .billing-title {
          font-size: 0.75rem;
          color: var(--text-muted);
          text-transform: uppercase;
          margin-bottom: 8px;
        }

        .billing-flow {
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-size: 0.8rem;
        }

        .bf-party {
          font-weight: 600;
          color: var(--text-secondary);
        }

        .bf-party.mine {
          color: var(--primary);
        }

        .bf-arrow {
          font-size: 0.7rem;
          color: var(--text-muted);
          animation: pulseGlow 3s infinite;
        }

        /* Section Layouts */
        .section-title-center {
          text-align: center;
          max-width: 600px;
          margin: 0 auto 60px;
        }

        .section-title-center h2 {
          font-size: 2.25rem;
          margin-bottom: 12px;
        }

        .section-title-center p {
          color: var(--text-secondary);
        }

        /* Comparison table styling */
        .comparison-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 32px;
          max-width: 900px;
          margin: 0 auto;
        }

        @media (max-width: 768px) {
          .comparison-grid {
            grid-template-columns: 1fr;
          }
        }

        .comparison-card {
          padding: 40px;
          position: relative;
        }

        .highlighted-card {
          border-color: var(--primary);
          box-shadow: 0 8px 32px var(--primary-glow-subtle);
          background: rgba(13, 42, 34, 0.4);
        }

        .card-top-tag {
          position: absolute;
          top: 16px;
          right: 16px;
          background: var(--primary);
          color: var(--bg-primary);
          font-size: 0.7rem;
          font-weight: 700;
          text-transform: uppercase;
          padding: 4px 10px;
          border-radius: 100px;
          letter-spacing: 0.05em;
        }

        .comp-card-header {
          margin-bottom: 32px;
        }

        .comp-badge {
          font-size: 0.75rem;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          color: var(--text-muted);
          display: block;
          margin-bottom: 8px;
        }

        .highlighted-card .comp-badge {
          color: var(--primary);
        }

        .comp-card-header h3 {
          font-size: 1.6rem;
        }

        .comp-points {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }

        .comp-point-row {
          display: flex;
          justify-content: space-between;
          align-items: center;
          border-bottom: 1px solid rgba(255, 255, 255, 0.04);
          padding-bottom: 12px;
        }

        .pt-label {
          font-size: 0.9rem;
          color: var(--text-secondary);
        }

        .pt-val-wrap {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .pt-icon {
          width: 20px;
          height: 20px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 0.75rem;
          font-weight: 700;
        }

        .pt-icon.check {
          background: rgba(0, 230, 153, 0.1);
          color: var(--primary);
        }

        .pt-icon.cross {
          background: rgba(255, 255, 255, 0.05);
          color: var(--text-muted);
        }

        .pt-value {
          font-size: 0.9rem;
          font-weight: 500;
        }

        .pt-value.green {
          color: var(--text-primary);
        }

        .pt-value.muted {
          color: var(--text-muted);
        }

        /* Projects Section styling */
        .project-card {
          padding: 0;
          border-radius: var(--border-radius-md);
        }

        .project-img-placeholder {
          height: 160px;
          width: 100%;
          position: relative;
          border-radius: var(--border-radius-md) var(--border-radius-md) 0 0;
          overflow: hidden;
        }

        .proj-status-tag {
          position: absolute;
          top: 12px;
          right: 12px;
          font-size: 0.7rem;
          font-weight: 600;
          background: rgba(6, 12, 23, 0.85);
          backdrop-filter: blur(4px);
          -webkit-backdrop-filter: blur(4px);
          padding: 4px 10px;
          border-radius: 100px;
          color: var(--primary);
          border: 1px solid var(--forest-border);
        }

        .proj-details {
          padding: 24px;
        }

        .proj-loc {
          font-size: 0.8rem;
          color: var(--text-muted);
          margin-bottom: 8px;
        }

        .project-card h3 {
          font-size: 1.25rem;
          margin-bottom: 4px;
        }

        .proj-partner {
          font-size: 0.8rem;
          color: var(--text-secondary);
          margin-bottom: 20px;
        }

        .proj-specs {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 16px;
          border-top: 1px solid rgba(255, 255, 255, 0.05);
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
          padding: 16px 0;
          margin-bottom: 20px;
        }

        .ps-lbl {
          display: block;
          font-size: 0.75rem;
          color: var(--text-muted);
          text-transform: uppercase;
        }

        .ps-val {
          font-weight: 600;
          font-size: 0.95rem;
          color: var(--text-primary);
        }

        .proj-progress-wrap {
          margin-bottom: 24px;
        }

        .progress-lbl-row {
          display: flex;
          justify-content: space-between;
          font-size: 0.8rem;
          color: var(--text-secondary);
          margin-bottom: 8px;
        }

        .progress-track {
          height: 6px;
          background: rgba(255, 255, 255, 0.05);
          border-radius: 3px;
          overflow: hidden;
        }

        .progress-bar {
          height: 100%;
          background: linear-gradient(90deg, var(--primary), var(--secondary));
          border-radius: 3px;
        }

        .btn-proj {
          width: 100%;
          padding: 10px 0;
        }

        /* FAQ Section elements */
        .faq-list {
          max-width: 800px;
          margin: 0 auto;
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .faq-item {
          background: rgba(255, 255, 255, 0.01);
          border: 1px solid var(--card-border);
          border-radius: var(--border-radius-sm);
          overflow: hidden;
          transition: var(--transition-smooth);
        }

        .faq-item:hover, .faq-item-open {
          border-color: rgba(0, 230, 153, 0.2);
          background: rgba(15, 28, 51, 0.25);
        }

        .faq-question {
          width: 100%;
          padding: 24px;
          display: flex;
          justify-content: space-between;
          align-items: center;
          text-align: left;
          color: var(--text-primary);
          font-family: var(--font-family-title);
          font-weight: 600;
          font-size: 1.1rem;
        }

        .faq-chevron {
          color: var(--text-muted);
          transition: var(--transition-smooth);
        }

        .faq-item-open .faq-chevron {
          transform: rotate(180deg);
          color: var(--primary);
        }

        .faq-answer-container {
          max-height: 0;
          overflow: hidden;
          transition: max-height 0.3s cubic-bezier(0, 1, 0, 1);
        }

        .faq-item-open .faq-answer-container {
          max-height: 1000px;
          transition: max-height 0.3s cubic-bezier(1, 0, 1, 0);
        }

        .faq-answer {
          padding: 0 24px 24px;
          color: var(--text-secondary);
          font-size: 0.95rem;
          line-height: 1.6;
          border-top: 1px solid rgba(255, 255, 255, 0.03);
          padding-top: 16px;
        }
      `}</style>
    </>
  );
}
